openapi: 3.0.3
info:
  title: Seller Service API
  description: Сервис управления компаниями и их услугами для платформы онлайн-записи на автомойку
  version: 1.0.0

servers:
  - url: http://localhost:8083/api/v1
    description: Development server



paths:
  /companies/{companyId}:
    parameters:
      - $ref: '#/components/parameters/CompanyIdParam'

    get:
      summary: "Получение компании по ID"
      operationId: getCompany
      tags:
        - Companies
      responses:
        '200':
          description: "Данные компании"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        '404':
          $ref: '#/components/responses/NotFound'

  /companies/{companyId}/services:
    parameters:
      - $ref: '#/components/parameters/CompanyIdParam'

    get:
      summary: "Получение списка услуг компании"
      operationId: listServices
      tags:
        - Services
      parameters:
        - $ref: '#/components/parameters/XUserIdHeaderOptional'
      responses:
        '200':
          description: "Список услуг"
          content:
            application/json:
              schema:
                type: object
                properties:
                  services:
                    type: array
                    items:
                      $ref: '#/components/schemas/Service'
        '404':
          $ref: '#/components/responses/NotFound'

  /companies/{companyId}/services/{serviceId}:
    parameters:
      - $ref: '#/components/parameters/CompanyIdParam'
      - $ref: '#/components/parameters/ServiceIdParam'

    get:
      summary: "Получение услуги по ID"
      operationId: getService
      tags:
        - Services
      parameters:
        - $ref: '#/components/parameters/XUserIdHeaderOptional'
      responses:
        '200':
          description: "Данные услуги"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    Company:
      type: object
      required:
        - id
        - name
        - description
        - addresses
        - working_hours
        - manager_ids
      properties:
        id:
          type: integer
          format: int64
          example: 1234567890
        name:
          type: string
          minLength: 1
          maxLength: 200
          example: "Автомойка Премиум"
        logo:
          type: string
          format: uri
          nullable: true
          example: "https://storage.example.com/logos/company-123.png"
        description:
          type: string
          minLength: 1
          maxLength: 2000
          example: "Профессиональная автомойка и детейлинг в центре Москвы"
        tags:
          type: array
          items:
            type: string
            pattern: '^#[а-яА-Яa-zA-Z0-9_]+$'
          example: ["#мойка", "#детейлинг", "#москва", "#премиум"]
        addresses:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Address'
        working_hours:
          $ref: '#/components/schemas/WorkingHours'
        manager_ids:
          type: array
          description: "User IDs менеджеров с доступом к управлению компанией"
          items:
            type: integer
            format: int64
          example: [123456789]
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true

    Address:
      type: object
      required:
        - id
        - city
        - street
        - building
        - coordinates
      properties:
        id:
          type: integer
          format: int64
          example: 9876543210
        city:
          type: string
          example: "Москва"
        street:
          type: string
          example: "Тверская улица"
        building:
          type: string
          example: "10к1"
        coordinates:
          $ref: '#/components/schemas/Coordinates'

    Coordinates:
      type: object
      required:
        - latitude
        - longitude
      properties:
        latitude:
          type: number
          format: double
          minimum: -90
          maximum: 90
          example: 55.755826
        longitude:
          type: number
          format: double
          minimum: -180
          maximum: 180
          example: 37.617299

    WorkingHours:
      type: object
      description: "Рабочие часы по дням недели"
      required:
        - monday
        - tuesday
        - wednesday
        - thursday
        - friday
        - saturday
        - sunday
      properties:
        monday:
          $ref: '#/components/schemas/DaySchedule'
        tuesday:
          $ref: '#/components/schemas/DaySchedule'
        wednesday:
          $ref: '#/components/schemas/DaySchedule'
        thursday:
          $ref: '#/components/schemas/DaySchedule'
        friday:
          $ref: '#/components/schemas/DaySchedule'
        saturday:
          $ref: '#/components/schemas/DaySchedule'
        sunday:
          $ref: '#/components/schemas/DaySchedule'

    DaySchedule:
      type: object
      required:
        - isOpen
      properties:
        isOpen:
          type: boolean
          example: true
        openTime:
          type: string
          pattern: '^([0-1][0-9]|2[0-3]):[0-5][0-9]$'
          example: "09:00"
          description: "Требуется если isOpen=true"
        closeTime:
          type: string
          pattern: '^([0-1][0-9]|2[0-3]):[0-5][0-9]$'
          example: "21:00"
          description: "Требуется если isOpen=true"

    Service:
      type: object
      required:
        - id
        - company_id
        - name
        - description
        - address_ids
      properties:
        id:
          type: integer
          format: int64
          example: 5555555555
        company_id:
          type: integer
          format: int64
          example: 1234567890
        name:
          type: string
          minLength: 1
          maxLength: 200
          example: "Комплексная мойка"
        description:
          type: string
          minLength: 1
          maxLength: 1000
          example: "Полная мойка кузова, дисков, ковриков и салона"
        average_duration:
          type: integer
          description: "Среднее время выполнения услуги в минутах"
          minimum: 1
          nullable: true
          example: 60
        address_ids:
          type: array
          description: "ID адресов из Company.addresses, где оказывается услуга"
          minItems: 1
          items:
            type: integer
            format: int64
          example: [9876543210]
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        price:
          type: number
          format: double
          nullable: true
          description: "Цена услуги (опционально, заполняется при наличии X-User-ID через интеграцию с PriceService)"
          example: 1500.00
        currency:
          type: string
          nullable: true
          description: "Валюта цены (опционально)"
          example: "RUB"
        pricing_type:
          type: string
          nullable: true
          description: "Тип ценообразования (опционально)"
          example: "fixed"
        vehicle_class:
          type: string
          nullable: true
          description: "Класс автомобиля пользователя (опционально)"
          example: "sedan"
        applied_multiplier:
          type: number
          format: double
          nullable: true
          description: "Применённый множитель к цене (опционально)"
          example: 1.2

  responses:
    NotFound:
      description: "Ресурс не найден"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: "NOT_FOUND"
            message: "Resource not found"

  parameters:
    XUserIdHeaderOptional:
      name: X-User-ID
      in: header
      required: false
      schema:
        type: integer
        format: int64
      description: "ID текущего пользователя (опционально, используется для получения цен от PriceService)"